sonar.projectKey=tanguy-tasklist-frontend
sonar.projectName=tanguy - TaskList Frontend

sonar.sources=src
sonar.tests=src/__tests__
sonar.test.inclusions=src/__tests__/**/*.test.tsx,src/__tests__/**/*.test.ts

sonar.exclusions=node_modules/**,dist/**,coverage/**,**/*.config.ts,**/*.config.js
sonar.test.exclusions=node_modules/**,dist/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
sonar.cpd.exclusions=src/__tests__/**